### ISSUE TITLE
Export error in streamdeck-events package

### ISSUE THREAD

**Issue by SO-Eng** [rweich/streamdeck-emulator#15]
Hey @rweich 

first I have to say, really great stuff you doing! It helps me a lot with development of a plugin for the streamdeck! Great work!
It's so lovely to work with TypeScript and it's really well to understand your packages!

Now I have a problem with this package. I downloaded it and try to start the server with this script:

"scripts": {
"start": "ts-node src/index.ts ../streamdeck-timetracking-plugin_1.0/dist/dev.com.softwort.timetracking.action.sdPlugin/plugin.html",
...
}

First I got an error with ts-node:
> @rweich/streamdeck-emulator@0.0.0-development start
> ts-node src/index.ts ../streamdeck-timetracking-plugin_1.0/dist/dev.com.softwort.timetracking.action.sdPlugin/plugin.html

/Users/softwort/dev/elgato/streamdeck/streamdeck-emulator-main/node_modules/typescript/lib/typescript.js:43500
        ts.Debug.assert(typeof typeReferenceDirectiveName === "string", "Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.");
....
many other stuff below.

Then i updated typescript with
yarn add typescript@latest ts-node@latest --dev

Now I getting this error: (I also get this with NPM - what I first tried. There I did not have the TipeScript issue above^^)

And getting this error from your '@rweich/streamdeck-events' package in node-modules folder:

yarn start

> @rweich/streamdeck-emulator@0.0.0-development start
> ts-node src/index.ts ../streamdeck-timetracking-plugin_1.0/dist/dev.com.softwort.timetracking.action.sdPlugin/plugin.html

/Users/softwort/dev/elgato/streamdeck/streamdeck-emulator-main/node_modules/@rweich/streamdeck-events/dist/index.js:1
export { default as EventsReceived } from "./Events/EventsReceived";
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/softwort/dev/elgato/streamdeck/streamdeck-emulator-main/src/Emulator.ts:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)

Now I stuck - Can you confirm this, or maybe help me here?

Greetings 
Markus

**Comment by rweich** [comment]
Heya @SO-Eng,

I'm glad that you find some of my projects useful (I assume, that you're talking about my other ones ;)).

Sadly I don't have any good news for this one, as its current state is nowhere near to be called usable. I've only created this for fun and the last time I've touched this, was a year ago (with no plans to change this any time soon).

While there is a way to get this kinda working (with some manual steps which are more pain than gain), I suggest to use the built-in debugging capabilities as described [here](https://docs.elgato.com/sdk/plugins/getting-started#5.-debugging) - which is what I usually do.

Greetings

**Comment by SO-Eng** [comment]
Hey @rweich 

Thank's for your answer and sorry for my late reply!
Finally I finished the plugin project on thursday already. Of course with the bad habit of closing and reopening Streamdeck all the time. So if this package would work, it would be awesome. But I understand your concerns absolutely. There are not many ppl out there to support with this! :)

Another question I have.

I  made a stopwatch, a plugin that is connected to our time tracking app (from the company who I'm working for). It was mor a fun project, has a lot of overtime, took that for me and of course I coded private again :D 
So I also had many looks to your [DateTime](https://github.com/rweich/streamdeck-datetime) project.

My biggest issue was the interval (timeout also have problems) in the plugin. It stopped always after 4:30 min (plus minus 5 seconds) and then refreshed the canvas after every minute. Took me a lot of time to fix this.
At the end I found that repo from Elgato itself [Timerfix](https://github.com/elgatosf/streamdeck-timerfix) and implemented this. Then it worked well.
Do you have found similar achievements?

If you have interest, I could quick make a PR to add the timerfix to [TS-Template](https://github.com/rweich/streamdeck-ts) or/and the DateTime project.
Bcs. it tooks me very much time to get around this :/

Greetings
Markus

**Comment by rweich** [comment]
Heya @SO-Eng,

Yeah, that closing/reopening was what basically made me start this side-project ^^
So just as a quicktip: you can reload your plugin through reloading the chrome-debugger-tab (or whatever browser you use for debugging - I guess), when you're in the ispect-your-plugin view. That works for me most times, thus removing the need to quit and reopen the streamdeck app on every change.

I've had the same timer issue on my other plugins, so I've created the [webworker-timer](https://github.com/rweich/webworker-timer/) project (which is basically the timerfix in TS). That fixed my issues with timers/intervals. I think that's used in the datetime project as well. Sad to hear you've lost time with this as well, maybe that need some highlighting in the ts-template.

Cheers

**Comment by SO-Eng** [comment]
Hey @rweich 

dang .... Ah okay, did not recognize that package. Checked the imports now and yeah, setInterval is imported from that package :/
But great! Then I know you struggled also there and you already have a solution!

Thank you for your support!
I'll close this than and keep going that great work!

Greetings
